pipeline {
    agent any
    stages {
        stage("npm install") {
            steps {
                sh "npm ci"
            }
        }
        stage("Lint commit") {
            steps {
                sh "npm run lint:commit"
            }
        }
        stage('Publish') {
            environment {
                NPM_TOKEN=credentials('NPM_TOKEN')
                GITHUB_TOKEN=credentials('GITHUB_TOKEN')
                GIT_TAG = sh(returnStdout: true, script: "git tag --contains").trim()
            }
            when {
                expression { env.GIT_TAG == null }
            }
            steps {
                sh "printenv"
                withCredentials([gitUsernamePassword(credentialsId: 'github-credentials', gitToolName: 'Default')]) {
                    sh "npm run release"
                }
            }
        }
    }
}