pipeline {
    agent any
    environment {
        OWNER: "lexedwards"
        REPO: "testpkg"
    }
    stages {
        stage("Variables") {
            steps {
                sh "printenv"
            }
        }
        stage("Version Check") {
            steps {
                sh "node --version"
                sh "npm --version"
                sh "git --version"
            }
        }
    }
}